plugins: rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Metrics:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
